export const useExperiences = () => [
    {
        position: "Senior Software Developer",
        tab: "Vocphone",
        company: "Vocphone",
        workStart: "Nov. 2021",
        workUntil: '<span class="present-work">Present</span>',
        des: "Full Time <b>Senior Software Developer</b> at <a href='https://www.vocphone.com/' target='_blank'>Vocphone</a>. Responsibilities are to design and implement complex business software problems and lease with management and the end customer.",
        url: "https://www.vocphone.com/",
    },
    {
        position: "Web Developer",
        tab: "Webinarinc",
        company: "Webinarinc",
        workStart: "Mar. 2021",
        workUntil: "Nov. 2021",
        des: "Full Time <b>Web Developer</b> at Webinarinc. We focus on developing/debugging/fixing websites, using different technologies to satisfy customers.",
        url: "https://webinarinc.com/",
    },
    {
        present: true,
        position: "Software Developer",
        tab: "Utalk",
        company: "Utalk",
        workStart: "August 2019",
        workUntil: "April 2021",
        des: "Maintaining Systems and services to lower the rate of system errors or bugs. We manage, maintain and develop front-end and back-end codes/programs. Engaged in different kinds of frameworks and tools like VueJs, AngularJs, Codeigniter, Lumen/Laravel, and Ruby on Rails. For the Database, we manage MySQL and Mongo Database.",
        url: "https://www.facebook.com/utalkphilippines",
        certificate: {
            link: "https://drive.google.com/file/d/1_CBroR0xY8bq9Z6kcS40opEQf_SC5AZ6/view?usp=sharing",
            label: "Show Employment Certificate",
        },
    },
    {
        position: "Web Developer",
        tab: "Dap-ayan",
        company: "Dap-ayan",
        workStart: "Aug. 2018",
        workUntil: "May 2019",
        des: "Participated as an author and a project developer for the Ordering Management System for the restaurant. We used PHP, JavaScript, HTML, CSS, and MySQL to build the web app.",
        url: "https://www.facebook.com/DapayanCafeExtention",
        certificate: {
            link: "https://drive.google.com/file/d/1TYyF6q4L2NdaXbibUry22UWC7YQpmzPN/view?usp=sharing",
            label: "Show Certificate of Participation",
        },
    },
    {
        position: "Designer and Web Programmer",
        tab: "iLearn",
        company: "iLearn",
        workStart: "September. 2018",
        workUntil: "Dec. 2018",
        des: "Being a part of a work that focuses on designs, I have been creating designs for simple magazines using Photoshop and Illustrator. Engaged in Video Editing using Adobe Premiere. Engaged in web programming using JavaScript and PHP.",
        url: "http://www.ilearnsda.com",
        certificate: {
            link: "https://drive.google.com/file/d/1NMz6G-fDcArzRm9odSfL_ntx5Hj0qLu_/view?usp=sharing",
            label: "Show Certificate of Completion",
        },
    },
    {
        position: "Web Developer Student",
        tab: "KCP",
        company: "KCP",
        workStart: "Aug. 2016",
        workUntil: "April 2019",
        des: `I have been a Full-time student at <a href='https://kcp.edu.ph' target='_blank'>Kings College of the Philippines</a>. It is the school where I started learning and experienced programming in Web Development.<br><br>King’s College of the Philippines is a mission school under the auspices of the Northern Luzon Presbyterian Church. Its beginnings can be traced to the arrival of a Korean Missionary, Rev. Kwon Young-Soo in the Philippines in 1991.<br><br>For more than a decade, Missionary Kwon laboriously ministered to a great number of people in the various Cordillera provinces namely: Mt. Province, Kalinga, Apayao, Ifugao, Benguet, Isabela, Cagayan, and also Baguio City. Noting the lack of trained clergy, Rev. Kwon established a Bible School named Zoe Logos Temple Ministry in Sabangan, Mt. Province. Eventually, to address the concern of the growing number of unschooled youth in the Cordilleras, and with assistance from a church and individual sponsors – local and overseas, he established Eastern Luzon Colleges in Bambang, Nueva Vizcaya in 2003 and Eastern Luzon Colleges in 2004 in La Trinidad, Benguet.`,
        url: "https://kcp.edu.ph/",
        certificate: {
            link: "https://drive.google.com/file/d/1p7I8t2maRU5vXJYjdE2-Cw1SiJJOVyYd/view?usp=sharing",
            label: "Show Certificate of Fulfillment",
        },
    },
];
